Bugfix: unexpected global package import
da-h/miniflask pull request #114
Opened 2022-10-05 14:57 UTC by da-h

# Bugfix: Unreliable imports.

This MR finalizes #112 by fixing an unexpected global package-import instead of a local minifflask module.

## Description

From #112 on, miniflask tries to use pythons `import` statement if possible to load modules.
The solution was to import the module name using the `importname`, i.e. without the module-base-directory in its identifier. Interestingly, this indeed loaded the correct modules in most cases.
However, in case a system-module with that name exists, miniflask would load that instead of the local module.

**Setup**:
1. Install any python package under the name `setup`.
2. Run `pytest`.

**Problem**:
Due to a module under `./tests/event/beforeafter/modules` named `setup`, the setup above will result in an error.

## Things done in this MR
The solution is quite simple: the module-`id` actually contains the base-directory name (in case the module directory has not been named otherwise in the `mf.init`-call - thus the string is correct in exactly those cases in which we want the internal `import` to be used.

**Check all before creating this PR**:
- [ ] Documentation adapted
- [ ] unit tests adapted / created

2022-10-05 15:01 UTC, da-h commented
Just a side-note: The linting errors (solved in #113) will throw errors here.
I will rebase whenever #113 is merged.

2022-10-05 20:22 UTC, sbrodehl requested changes
Looks good so far, just two comments in the code on possibly duplicated code and regarding the renaming of modules in the mf.init-call.

2022-10-05 20:22 UTC, sbrodehl commented on src/miniflask/miniflask.py
> +            return import_module(module_spec["id"])
Is there special care needed in case the module directory has been renamed in the mf.init-call?

2022-10-06 09:53 UTC, da-h commented on src/miniflask/__init__.py
> +        }
That's indeed a mistake. Thanks for pointing this out!

2022-10-06 10:15 UTC, sbrodehl commented on src/miniflask/miniflask.py
> +            return import_module(module_spec["id"])
Thanks for clarifying! That would be an interesting way foreward, let's discuss this further in another PR/Issue.

2022-10-06 10:25 UTC, da-h commented
Rebased onto master.

2022-10-06 10:30 UTC, sbrodehl approved these changes

2022-10-06 10:30 UTC, merged